### ISSUE TITLE
The first comment shows only when page is refreshed

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/ajax_comments#10]
Subj. Tested on a fresh Backdrop setup. The first comment (or multiple) never show unless you refresh the respective page. After the refresh everything works as expected.

So the first test comment in the below screenshot did not show up until the page was refreshed. Comments 2 and 3 showed as expected without page refresh.

<img width="904" alt="Screenshot 2023-08-16 at 10 43 36 PM" src="https://github.com/backdrop-contrib/ajax_comments/assets/56604405/042e5649-b49c-4b26-a7eb-5f7f7694042a">

**Comment by alanmels** [comment]
The https://docs.backdropcms.org/api/backdrop/core%21modules%21comment%21comment.theme.inc/1 lists only three functions available:



template_preprocess_comment | Preprocesses variables for comment.tpl.php.
-- | --
theme_comment_block | Returns HTML for a list of recent comments.
theme_comment_post_forbidden | Returns HTML for a "you can't post comments" notice.

[template_preprocess_comment](https://docs.backdropcms.org/api/backdrop/core%21modules%21comment%21comment.theme.inc/function/template_preprocess_comment/1) 	Preprocesses variables for [comment.tpl.php](https://docs.backdropcms.org/api/backdrop/1/search/comment.tpl.php).
[theme_comment_block](https://docs.backdropcms.org/api/backdrop/core%21modules%21comment%21comment.theme.inc/function/theme_comment_block/1) 	Returns HTML for a list of recent comments.
[theme_comment_post_forbidden](https://docs.backdropcms.org/api/backdrop/core%21modules%21comment%21comment.theme.inc/function/theme_comment_post_forbidden/1) 	Returns HTML for a "you can't post comments" notice.

So apparently the `template_preprocess_comment_wrapper()` of Drupal 7 was dropped on Backdrop, therefore the `ajax_comments_preprocess_comment_wrapper(&$variables)` never kicks in.

**Comment by alanmels** [comment]
After reading https://docs.backdropcms.org/change-records/new-layout-module-implements-a-drag-drop-model-for-building-layouts I came to conclusion that the least intrusive way to address this issue would be implementing the `hook_preprocess_page()` not to deal with layouts, because websites can change their layout templates and the solution needed to be universal.

**Comment by laryn** [comment]
@alanmels I never got back to this project and haven't needed it on a client project recently, but I was investigating the same issue over here, I think:

 - https://github.com/backdrop-contrib/ajax_comments/issues/7

I don't know that I found anything that you haven't already discovered. Feel free to close that other issue and rough work-in-progress PR as you see fit.
