### ISSUE TITLE
Some functions are never triggered

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/ajax_comments#16]
While working on other issues I've realized the functions like, for example, `ajax_comments_comment_insert($comment)`, `ajax_comments_comment_update($comment)` are never triggered. Inserting checks inside them didn't work. Also temporarily removing them altogether didn't effect anything.

**Comment by alanmels** [comment]
Another functions that simply doesn't work is `ajax_comments_remove_status()`.

**Comment by alanmels** [comment]
There were no such functions on Drupal 7 https://git.drupalcode.org/project/ajax_comments/-/blob/7.x-1.x/ajax_comments.module?ref_type=heads The https://github.com/backdrop-contrib/ajax_comments/blame/1.x-1.x/ajax_comments.module#L538 shows those functions were introduced as part of the solution for https://github.com/backdrop-contrib/ajax_comments/issues/6, however whatever I did none of those functions got triggered. So before removing them altogether, I'd love to hear from you @laryn on this. Thanks!

**Comment by alanmels** [comment]
Could you add those functions because you were trying to resolve https://github.com/backdrop-contrib/ajax_comments/issues/10#issuecomment-1682288526, which eventually had been resolved slightly differently by https://github.com/backdrop-contrib/ajax_comments/commit/407b44109400437432a48cec4184ab393888afc8? In that case, do I assume it is safe to remove those functions?

**Comment by laryn** [comment]
@alanmels It's been a while but I looked at the functions you mention, and I think it's an attempt to clear the comment caches using `hook_comment_insert` and `hook_comment_update`:
 - https://docs.backdropcms.org/api/backdrop/core%21modules%21comment%21comment.api.php/function/hook_comment_insert/1
 - https://docs.backdropcms.org/api/backdrop/core%21modules%21comment%21comment.api.php/function/hook_comment_update/1

The code comments around these functions also links here, for more context:
 - https://github.com/backdrop/backdrop-issues/issues/5335

As far as `ajax_comments_remove_status()` I don't think I changed the implementation from what exists in Drupal 7, but if it doesn't work, feel free to modify.

**Comment by alanmels** [comment]
@laryn, thank you for the details. 

I am afraid both functions are never triggered. Please place a simple dpm('test') check inside of them and it will never come up. I'm not sure how exactly the module bypasses the hooks, but it might by having such special functions like: `function ajax_comments_preview_js($form, &$form_state)` and `function ajax_comments_submit_js($form, &$form_state)` implemented.

Please note that after https://github.com/backdrop-contrib/ajax_comments/commit/407b44109400437432a48cec4184ab393888afc8 there is no need to clear cache as running multiple tests shown all posts including the very first are appearing on UI without issues. The whole attempt to clear cache could have appeared because the first comment was not showing up before that commit.

Also please note that completely removing both functions didn't have any affect. Please run some tests on your end and confirm if we could clean up the code a bit and make another release. Thank you for your time and attention!

**Comment by laryn** [comment]
@alanmels I have no projects currently using this module and I trust your testing to determine when it's ready for a new release. 👍

**Comment by alanmels** [comment]
@laryn, thank you for giving me a green light for the next release. If we eventually end up needing those two functions we can always bring them back, so I'll go ahead to cleaning the code a bit and release the next official version later tonight.

**Comment by argiepiano** [comment]
Wait, @alanmels. I may be wrong with this, but this is module is using ajax to render some parts of the page, it is possible that dpm will never output anything (because the dpm output is not being rendered by the ajax layer).

A better way to test this is to use `watchdog` and then check the log. I've been bitten by this in the past - dpm is not a good way to test ajax stuff. Alternatively, you can use step debug to check if the functions are really not being called.

Apologies if I'm missing part of the conversation here.

**Comment by alanmels** [comment]
@argiepiano, further troubleshooting this at some point I realized that `dpm()` was not the right tool to test it, however as I mentioned before the functions `ajax_comments_comment_insert($comment)` and `ajax_comments_comment_update($comment)` were not on Drupal 7 version, they were introduced later on Backdrop possibly in an attempt to make the first comment appear. However, after that problem was solved in a different way (see https://github.com/backdrop-contrib/ajax_comments/commit/407b44109400437432a48cec4184ab393888afc8), everything started working as expected and there was no need to clear cache anymore. So none of two functions are really needed.

The problem I'm now working one is elsewhere - the status messages appearing after comment actions are quite confused and overlap each other. For example, despite the module originally had these functions, where all status messages logic could be considered:

```php
/**
 * Implements hook_theme().
 */
function ajax_comments_theme($existing, $type, $theme, $path) {
  return array(
    'ajax_comments_notify_text' => array(
      'variables' => array('type' => NULL, 'comment' => NULL),
    ),
  );
}

/**
 * Returns text to notify user their comment has been added.
 */
function theme_ajax_comments_notify_text($vars = array()) {
  $text = t('Your comment has been posted.');
  $status = 'status';
  // If the comment is unapproved, alter the message
  if (isset($vars['comment']) && !$vars['comment']->status) {
    $text = t('Your comment has been queued for review by site administrators and will be published after approval.');
    $status = 'warning';
  }
  if ($vars['type'] == 'delete') {
    $text = t('Your comment has been deleted');
  }
  elseif ($vars['type'] == 'preview') {
    $text = t('This is the preview for your comment. You must click SAVE or your comment will be lost.');
    $status = 'warning';
  }
  backdrop_set_message($text, $status);
  return theme('status_messages');
}
```

the following additional functions were introduced at https://github.com/backdrop-contrib/ajax_comments/blob/841a52e61e1d5da6a64b3b16a416d3f6883c0cd4/ajax_comments.module#L332C3-L337C1 with clear doubt of the committer in the commented section:

```php
// This is to remove the "Your comment has been posted" status message that
  // will appear upon refresh. This seems dirty but it means we don't have to
  // rewrite the whole comment_form_submit(). Please chime in if you think this
  // is dumb.
  ajax_comments_remove_status();
```

with the function itself looking like this further down in the module's code:

```php
/**
 * Removes "Your comment has been posted." or "Your comment has been queued.."
 *   from the status message.
 */
function ajax_comments_remove_status() {
  if (!empty($_SESSION['messages']['status'])) {
    $deleted = t('The comment and all its replies have been deleted.');
    $published = t('Your comment has been posted.');
    $not_published = t('Your comment has been queued for review by site administrators and will be published after approval.');
    foreach ($_SESSION['messages']['status'] as $key => $value) {
      if ($value == $published || $value == $not_published || $value = $deleted) {
        unset($_SESSION['messages']['status'][$key]);
      }
    }
    if (empty($_SESSION['messages']['status'])) {
      unset($_SESSION['messages']['status']);
      if (empty($_SESSION['messages'])) {
        unset($_SESSION['messages']);
      }
    }
  }
}
```
