### ISSUE TITLE
Can't open comment

### ISSUE THREAD

**Issue by djzwerg** [backdrop-contrib/ajax_comments#3]
After leaving a reply/answer to a comment the page can't be loaded and the following error occurs:

Argument 3 passed to comment_new_page_count() must be an instance of Node, instance of stdClass given, called in /var/www/vhosts/mypath/modules/forum/forum.module on line 1163

**Comment by djzwerg** [comment]
I'm not sure whether this is an issue by AJAX comment or Forum module. Maybe it is related to https://github.com/backdrop/backdrop/pull/2235.

**Comment by laryn** [comment]
Looks like a forum issue based on the error message. Are you using 1.x or 2.x for the forum?

**Comment by djzwerg** [comment]
> 
> 
> Looks like a forum issue based on the error message. Are you using 1.x or 2.x for the forum?

I'm using 1.x-1.0.2.

**Comment by djzwerg** [comment]
@laryn if it is a forum issue I'm going to close this issue here.
