### ISSUE TITLE
Remove `template_preprocess_comment_wrapper`

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/ajax_comments#7]
The `template_preprocess_comment_wrapper` function doesn't exist anymore and needs to be moved into `hook_preprocess_node()` I think.

Reference: 

 - https://github.com/backdrop/backdrop/commit/e95a0c740d2405cfdaec8c16eb931c89d3aa4c11#diff-fe5bc1e17914f470574aa56e8771c4c2575fcb261a5d9840f8645e2ae1cd4e8a

**Comment by alanmels** [comment]
I didn't know it was the same issue I worked on yesterday. Well, since there is a working PR for the other issue, I'm closing this on in favor of https://github.com/backdrop-contrib/ajax_comments/issues/10.
