### ISSUE TITLE
Possible conflict with comment settings

### ISSUE THREAD

**Issue by sbgraphicdesign** [backdrop-contrib/ajax_comments#9]
I am experiencing problems with this module when choosing, in the Content Type Comments configuration, any other setting than "Anonymous posters may not enter their contact information".

On the node, the ajax comment form does not load and the 'reply' links load up the separate comment page.

In the browser console I see this error:

**Uncaught TypeError: $.cookie is not a function
attach http://localhost/Test/core/misc/form.js?v=1.21.1:133
each jQuery
attach http://localhost/Test/core/misc/form.js?v=1.21.1:131
jQuery 3
attach http://localhost/Test/core/misc/form.js?v=1.21.1:129
attachBehaviors http://localhost/Test/core/misc/backdrop.js?v=1.21.1:73
each jQuery
attachBehaviors http://localhost/Test/core/misc/backdrop.js?v=1.21.1:71
<anonymous> http://localhost/Test/core/misc/backdrop.js?v=1.21.1:699
jQuery 4**

I have tested this on a local build under Mamp with Backdrop 1.21.1 and latest version of ajax comments 1.x-1.3-alpha, with just core modules enabled.

**Comment by alanmels** [comment]
Unfortunately, the screenshots were never attached, so it's not possible to see what you meant. To clean up the issues queue, I will go ahead and close this issue. Some obsolete code blocks have been removed by the last commit, so please try the dev version to see if your problem persists and feel free to re-open the issue if it does.
